This notebook  gives the basic of arrya with axes. Using the Numpy package. 

In [ ]:
import numpy as np  #importing the numpy package where numpy stands as number with pyhon  

In [ ]:
np.array([24]) #its a single dimensional array with number that helps to print the array number 

array([24])

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([[1,1,1],[2,2,2]])

array([[1, 1, 1],
       [2, 2, 2]])

In [ ]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [ ]:
arr=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
arr.shape

(2, 2, 3)

In [ ]:
arr.ndim

3

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((1,1))

array([[1.]])

In [ ]:
np.ones((1,2))

array([[1., 1.]])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(3) #Identity matrix of 3*3 eye is the keyword used for the identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(5,5)

array([[0.69693367, 0.75097118, 0.95067476, 0.39426695, 0.8797948 ],
       [0.12866965, 0.6329631 , 0.99981698, 0.41972344, 0.69032918],
       [0.66671005, 0.81549536, 0.5413428 , 0.88952955, 0.86453136],
       [0.93131791, 0.46321372, 0.06913797, 0.93183823, 0.23631102],
       [0.53191555, 0.40992948, 0.81622063, 0.79347813, 0.55077681]])

In [ ]:
ranarr = np.random.randint(0,100,20)

In [ ]:
#The created random array.
ranarr

array([92, 84,  1, 49, 46, 14, 53, 59, 46,  2, 63,  9, 51, 78, 81, 56, 64,
       94, 75, 45])

In [ ]:
# Find the max value in the array
ranarr.max()

94

In [ ]:
# Find the index of the maximum value
ranarr.argmax()

17

In [ ]:
# Find the minimum value in the array
ranarr.min()

1

In [ ]:
# Find the index of the minimum value
ranarr.argmin()

2

In [ ]:
#Creating sample array
my_arr = np.arange(0,11)
# Check the array
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Get a value at an index
my_arr[8]

8

In [ ]:
#Get values in a range
my_arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
my_arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
#Setting a value with index range (Broadcasting)
my_arr[0:5]=100
#Show
my_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in a moment
my_arr = np.arange(0,11)
#Show
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = my_arr[0:6]
#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99
#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
my_arr
#array is created from the arr silce of 6 and 99

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#To get a copy, need to be explicit
arr_copy = my_arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]
# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

Arthmeetic Operations 

In [ ]:
import numpy as np
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

<ipython-input-52-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])